# **Computação II** <br/>
**Bachelor's Degree Programs in Data Science and Information Systems**<br/>
**NOVA IMS**<br/>

**NOTE:** Adapted from Prof. Dr. Illya Bakurov's class materials.

## References
1. [Python ``time`` module, official documentation](https://docs.python.org/3/library/time.html)
2. [Python ``timeit`` module, official documentation](https://docs.python.org/3/library/timeit.html)

# 1. Comparing algorithms' efficiency

Consider two functions that compute the primary or secondary diagonal of a squared matrix using Python base.

<center><img src="https://assets.leetcode.com/uploads/2020/08/14/sample_1911.png" width=300/></center>

Imports ``time`` and ``timeit`` modules to keep track of runtime. Also, imports ``numpy`` to generate random values, and ``matplotlib`` to draw plots.

In [2]:
import time 
import timeit
import numpy as np
import matplotlib.pyplot as plt

Creates an arbitrary matrix and computes the two diagonals using ``numpy``.

In [3]:
#matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix = np.random.randint(0, 20, size=(3, 3))
print("Matrix:\n", matrix)
print("Primary diagonal using NumPy: ", np.diag(matrix).sum())
print("Secondary diagonal using NumPy: ", np.diag(np.fliplr(matrix)).sum())

Matrix:
 [[17  9 19]
 [ 8  8 18]
 [ 8  2 14]]
Primary diagonal using NumPy:  39
Secondary diagonal using NumPy:  35


**The purpose of this exercise is to manually implement an efficient and effective function to compute the diagonal of a given squared matrix. Assume that the user can specify which diagonal he/she wants to compute with a parameter of the function.**

## 1.1. Naive approach
1. In order to iterate over the values of a $n \times n$ matrix, one needs to use nested for loops: 
    1. one to iterate over the rows (let $r$ represent the index of a row)
    2. another to iterate over the columns (let $c$ represent the index of a column)
2. The values on the primary diagonal correspond to the case when $r$ equals $c$
3. The values on the secondary diagonal correspond to the case when $r$ equals $n - 1 - c$

The time complexity for this algorithm can be defined as $T(n) = cn^2$.

In [53]:
def sum_diagonal_1(matrix, primary=True):
    diagonal_sum = 0
    # For each row 
    for r, row in enumerate(matrix):
        # For each column value at a given row 
        for c, col_value in enumerate(row):
            if primary:
                if r == c:
                    diagonal_sum += col_value
            elif r == len(row)-c-1: 
                diagonal_sum += col_value
    return diagonal_sum

Tests ``sum_diagonal_1()``.

In [48]:
start = time.time()
result = sum_diagonal_1(matrix, False)
end = time.time()-start
print("R: {}. The algorithm took {} seconds".format(result, end))

R: 32. The algorithm took 0.0 seconds


## 1.2. A more efficient approach
Actually, one can avoid using the inner loop to iterate over every single entry of a matrix. One can simply come up with an expression that is equivalent to $n - 1 - c$ using the row index $r$ alone. 

1. Iterate over the rows of a $n \times n$ matrix (let $r$ represent the index of a row)    
2. The values on the primary diagonal correspond to the case when $r$ equals $c$
3. The values on the secondary diagonal correspond to the case when $r$ equals $n - 1 - r$

Time complexity for this algorithm can be defined as $T(n) = cn$.

In [54]:
def sum_diagonal_2(matrix, primary=True):
    diagonal_sum = 0
    for r, row in enumerate(matrix):
        if primary:
            diagonal_sum += row[r]
        else:
            diagonal_sum += row[len(row)-1-r]
    return diagonal_sum

Tests ``sum_diagonal_2()``.

In [52]:
start = time.time()
result = sum_diagonal_2(matrix, False)
end = time.time()-start
print("R: {}. The algorithm took {} seconds".format(result, end))

R: 32. The algorithm took 0.0 seconds


## 2. The ``timeit`` module

The ``timeit`` module is an effective tool to measure the run time of **small** code snippets. It avoids a number of common issues for measuring execution times. 

Simply saving the time before and after the execution of the code snippet is not precise as there might be a background process momentarily running which can cause significant variations in the running time of small code snippets.

The ``timeit`` module allows you to run your snippet *many* times (default value is 1000000) so that you get the *expected* runtime (and other relevant measures). Visit the official documentation [2] for more details.

Tests ``sum_diagonal_1()``.

In [55]:
# Code snippet to be executed only once
setup1 = '''
import numpy as np

matrix = np.random.randint(0, 20, size=(100, 100))

def sum_diagonal_1(matrix, primary=True):
    diagonal_sum = 0
    for r, row in enumerate(matrix):
        for c, value in enumerate(row):
            if primary:
                if r == c:
                    diagonal_sum += value
            elif r == len(row)-1-c:
                diagonal_sum += value
    return diagonal_sum
'''

# Code snippet whose execution time is to be measured
snippet1 = '''sum_diagonal_1(matrix, False)'''

# The timeit statement
secs1 = timeit.timeit(setup=setup1, stmt=snippet1, number=1000)
print("The snippet \n\n\"\"\"{}\"\"\"\n\ntook {:.3f} seconds to execute".format(snippet1, secs1))

The snippet 

"""sum_diagonal_1(matrix, False)"""

took 1.689 seconds to execute


Tests ``sum_diagonal_2()``.

In [56]:
# Code snippet to be executed only once
setup2 = '''
import numpy as np

matrix = np.random.randint(0, 20, size=(100, 100))

def sum_diagonal_2(matrix, primary=True):
    diagonal_sum = 0
    for r, row in enumerate(matrix):
        if primary:
            diagonal_sum += row[r]
        else:
            diagonal_sum += row[len(row)-1-r]
    return diagonal_sum
'''

# Code snippet whose execution time is to be measured
snippet2 = '''sum_diagonal_2(matrix, False)'''

# The timeit statement
secs2 = timeit.timeit(setup=setup2, stmt=snippet2, number=1000)
print("The snippet \n\n\"\"\"{}\"\"\"\n\ntook {:.3f} seconds to execute".format(snippet2, secs2))

The snippet 

"""sum_diagonal_2(matrix, False)"""

took 0.036 seconds to execute
