# **Computação II** <br/>
**Bachelor's Degree Programs in Data Science and Information Systems**<br/>
**NOVA IMS**<br/>

**NOTE:** Adapted from Prof. Dr. Illya Bakurov's class materials.

## References
1. [Python ``time`` module, official documentation](https://docs.python.org/3/library/time.html)
2. [Python ``timeit`` module, official documentation](https://docs.python.org/3/library/timeit.html)

# 1. Comparing algorithms' efficiency

Consider two functions that compute the primary or secondary diagonal of a squared matrix using Python base.

<center><img src="https://assets.leetcode.com/uploads/2020/08/14/sample_1911.png" width=300/></center>

Imports ``time`` and ``timeit`` modules to keep track of runtime. Also, imports ``numpy`` to generate random values, and ``matplotlib`` to draw plots.

In [42]:
import time 
import timeit
import numpy as np
import matplotlib.pyplot as plt

Creates an arbitrary matrix and computes the two diagonals using ``numpy``.

In [43]:
matrix1 = np.random.randint(1,20,(4,4))
print(matrix1)
print()
print(np.diag(matrix1).sum())
print(np.diag(np.fliplr(matrix1)).sum())

[[17  7  9 15]
 [ 5 16  5  5]
 [19  7 16 16]
 [ 5 11  2 16]]

65
32


## 1.1. Naive approach

In [90]:
#matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix1 = np.random.randint(1,20,(4,4))
print(matrix1)

def primcalc(mat,prim = True):
    sum = 0
    if prim == True:
        for i in range(len(mat)):
            sum += mat[i][i]
    else:
        for i in range(len(mat)):
            sum += mat[i][len(mat) - i - 1]
    return sum

primcalc(matrix1,False)    


[[ 1  3 15 17]
 [14 10  1 13]
 [10 12  5 19]
 [ 3  6  5 16]]


33

Tests ``sum_diagonal_1()``.

In [118]:
timeit.timeit(lambda : primcalc(matrix1,False), number=100)

0.0002109999768435955

## 1.2. A more efficient approach

Tests ``sum_diagonal_2()``.

## 2. The ``timeit`` module

The ``timeit`` module is an effective tool to measure the run time of **small** code snippets. It avoids a number of common issues for measuring execution times. 

Simply saving the time before and after the execution of the code snippet is not precise as there might be a background process momentarily running which can cause significant variations in the running time of small code snippets.

The ``timeit`` module allows you to run your snippet *many* times (default value is 1000000) so that you get the *expected* runtime (and other relevant measures). Visit the official documentation [2] for more details.

Tests ``sum_diagonal_1()``.

Tests ``sum_diagonal_2()``.