# **Computation II** <br/>
**Bachelor's Degree Programs in Data Science and Information Systems**<br/>
**NOVA IMS**<br/>

**NOTE:** Some of the practical class materials were adapted from Prof. Dr. Illya Bakurov's class materials.

## Numpy

In [1]:
import numpy as np

#### Let's define a numpy array and print its length, shape, type and the type of the elements in the array.

#### Indexing

#### Question: Create a one dimensional numpy array and print only the values higher than the average

#### More on One Dimensional Arrays

In [2]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
np.random.random(10)

array([0.24011797, 0.57407184, 0.16918588, 0.44738231, 0.06086805,
       0.48915014, 0.03230793, 0.24635409, 0.72640075, 0.06622954])

In [5]:
first = np.ones(5)
second = np.ones(5)

#### Two Dimensional Arrays

In [6]:
my_array2d = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
my_array2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
# 3 x 4 array of ones


In [8]:
# 3 x 3 identity matrix


#### Indexing

#### More on two dimensional arrays

In [9]:
onesarray = np.ones([3,4])
onesarray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Transpose of an array


In [11]:
twod = np.zeros((5, 2))
twod

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
for i in range(twod.shape[0]):
    twod[i, :] = np.random.random(2)
twod

array([[0.74210656, 0.25692961],
       [0.23879203, 0.99182724],
       [0.98002732, 0.82396525],
       [0.01041626, 0.40262249],
       [0.38171384, 0.71529051]])

In [13]:
twod = np.random.random(size=(5,2))
twod

array([[0.51874395, 0.28249702],
       [0.82752771, 0.82126997],
       [0.91954686, 0.30850221],
       [0.52638103, 0.97672581],
       [0.20986261, 0.93587354]])

#### Arange and Reshape

#### Indexing

#### More

In [14]:
# unique, flip, where